### ISSUE TITLE
Overlapping ranges expected?

### ISSUE THREAD

**Issue by tbussmann** [sapics/ip-location-db#17]
First, thanks for providing these quite convenient datasets!

Unfortunately, I was unable to find the scripts that compile the combined databases from their source providers, so I can't check how they are working and what to expect as output.

For example I'm looking in the `geo-whois-asn-country-ipv4.csv` version of the database. Among the 261'576 records in the file (as of v2.3.2023051318) there are 83 overlapping ranges, caused by only 3 ranges:

from_ip | to_ip | country
-- | -- | --
5.57.16.0 | 5.57.22.255 | NL
77.70.128.0 | 77.70.143.255 | LU
193.109.186.0 | 193.109.186.255 | ES

As the number of overlaps is so small, these look like data or processing errors. Or are the consumers of the dataset meant to search for the most specific (smallest) range that matches a given IP?

Full list of overlaps:

from_ip | to_ip | country | from_ip_1 | to_ip_1 | country_1
-- | -- | -- | -- | -- | --
5.57.16.0 | 5.57.22.255 | NL | 5.57.17.0 | 5.57.22.255 | NL
5.57.16.0 | 5.57.16.255 | GB | 5.57.16.0 | 5.57.22.255 | NL
77.70.128.0 | 77.70.143.255 | LU | 77.70.134.0 | 77.70.134.47 | SS
77.70.128.0 | 77.70.143.255 | LU | 77.70.134.48 | 77.70.134.55 | GA
77.70.128.0 | 77.70.143.255 | LU | 77.70.134.56 | 77.70.134.63 | BF
77.70.128.0 | 77.70.143.255 | LU | 77.70.134.64 | 77.70.134.71 | NE
77.70.128.0 | 77.70.143.255 | LU | 77.70.134.72 | 77.70.134.75 | AF
77.70.128.0 | 77.70.143.255 | LU | 77.70.134.76 | 77.70.134.79 | AO
77.70.128.0 | 77.70.143.255 | LU | 77.70.134.80 | 77.70.134.99 | US
77.70.128.0 | 77.70.143.255 | LU | 77.70.134.100 | 77.70.134.103 | TF
77.70.128.0 | 77.70.143.255 | LU | 77.70.134.104 | 77.70.134.111 | BF
77.70.128.0 | 77.70.143.255 | LU | 77.70.134.112 | 77.70.134.119 | NO
77.70.128.0 | 77.70.143.255 | LU | 77.70.134.120 | 77.70.134.127 | BF
77.70.128.0 | 77.70.143.255 | LU | 77.70.134.128 | 77.70.134.143 | YE
77.70.128.0 | 77.70.143.255 | LU | 77.70.134.144 | 77.70.134.151 | BF
77.70.128.0 | 77.70.143.255 | LU | 77.70.134.152 | 77.70.134.155 | GB
77.70.128.0 | 77.70.143.255 | LU | 77.70.134.156 | 77.70.134.159 | NO
77.70.128.0 | 77.70.143.255 | LU | 77.70.134.160 | 77.70.134.175 | BF
77.70.128.0 | 77.70.143.255 | LU | 77.70.134.176 | 77.70.134.183 | NO
77.70.128.0 | 77.70.143.255 | LU | 77.70.134.184 | 77.70.134.199 | BF
77.70.128.0 | 77.70.143.255 | LU | 77.70.134.200 | 77.70.134.207 | CM
77.70.128.0 | 77.70.143.255 | LU | 77.70.134.208 | 77.70.134.215 | BF
77.70.128.0 | 77.70.143.255 | LU | 77.70.134.216 | 77.70.134.223 | SS
77.70.128.0 | 77.70.143.255 | LU | 77.70.134.224 | 77.70.134.231 | CD
77.70.128.0 | 77.70.143.255 | LU | 77.70.134.232 | 77.70.134.235 | FR
77.70.128.0 | 77.70.143.255 | LU | 77.70.134.236 | 77.70.134.239 | NO
77.70.128.0 | 77.70.143.255 | LU | 77.70.134.240 | 77.70.134.243 | GB
77.70.128.0 | 77.70.143.255 | LU | 77.70.134.244 | 77.70.134.247 | NO
77.70.128.0 | 77.70.143.255 | LU | 77.70.134.248 | 77.70.135.15 | US
77.70.128.0 | 77.70.143.255 | LU | 77.70.135.16 | 77.70.135.23 | BF
77.70.128.0 | 77.70.143.255 | LU | 77.70.135.24 | 77.70.135.31 | NO
77.70.128.0 | 77.70.143.255 | LU | 77.70.135.32 | 77.70.135.39 | CF
77.70.128.0 | 77.70.143.255 | LU | 77.70.135.40 | 77.70.135.47 | NO
77.70.128.0 | 77.70.143.255 | LU | 77.70.135.48 | 77.70.135.55 | CF
77.70.128.0 | 77.70.143.255 | LU | 77.70.135.56 | 77.70.135.63 | NO
77.70.128.0 | 77.70.143.255 | LU | 77.70.135.64 | 77.70.135.71 | US
77.70.128.0 | 77.70.143.255 | LU | 77.70.135.72 | 77.70.135.79 | CH
77.70.128.0 | 77.70.143.255 | LU | 77.70.135.80 | 77.70.135.87 | GN
77.70.128.0 | 77.70.143.255 | LU | 77.70.135.88 | 77.70.135.95 | GA
77.70.128.0 | 77.70.143.255 | LU | 77.70.135.96 | 77.70.135.103 | LB
77.70.128.0 | 77.70.143.255 | LU | 77.70.135.104 | 77.70.135.111 | CF
77.70.128.0 | 77.70.143.255 | LU | 77.70.135.112 | 77.70.135.123 | CD
77.70.128.0 | 77.70.143.255 | LU | 77.70.135.124 | 77.70.135.127 | US
77.70.128.0 | 77.70.143.255 | LU | 77.70.135.128 | 77.70.135.143 | MM
77.70.128.0 | 77.70.143.255 | LU | 77.70.135.144 | 77.70.135.151 | KM
77.70.128.0 | 77.70.143.255 | LU | 77.70.135.152 | 77.70.135.191 | GA
77.70.128.0 | 77.70.143.255 | LU | 77.70.135.192 | 77.70.135.239 | FR
77.70.128.0 | 77.70.143.255 | LU | 77.70.135.240 | 77.70.135.247 | CF
77.70.128.0 | 77.70.143.255 | LU | 77.70.135.248 | 77.70.136.127 | NO
77.70.128.0 | 77.70.143.255 | LU | 77.70.136.128 | 77.70.137.127 | US
77.70.128.0 | 77.70.143.255 | LU | 77.70.137.128 | 77.70.137.255 | SS
77.70.128.0 | 77.70.143.255 | LU | 77.70.138.0 | 77.70.138.4 | AO
77.70.128.0 | 77.70.143.255 | LU | 77.70.138.5 | 77.70.138.23 | AE
77.70.128.0 | 77.70.143.255 | LU | 77.70.138.24 | 77.70.141.255 | NO
77.70.128.0 | 77.70.143.255 | LU | 77.70.142.0 | 77.70.142.63 | CF
77.70.128.0 | 77.70.143.255 | LU | 77.70.142.64 | 77.70.142.71 | TD
77.70.128.0 | 77.70.143.255 | LU | 77.70.142.72 | 77.70.142.87 | BE
77.70.128.0 | 77.70.143.255 | LU | 77.70.142.88 | 77.70.142.95 | MZ
77.70.128.0 | 77.70.143.255 | LU | 77.70.142.96 | 77.70.142.103 | IT
77.70.128.0 | 77.70.143.255 | LU | 77.70.142.104 | 77.70.142.111 | KM
77.70.128.0 | 77.70.143.255 | LU | 77.70.142.112 | 77.70.142.119 | FR
77.70.128.0 | 77.70.143.255 | LU | 77.70.142.120 | 77.70.142.127 | NG
77.70.128.0 | 77.70.143.255 | LU | 77.70.142.128 | 77.70.142.135 | ML
77.70.128.0 | 77.70.143.255 | LU | 77.70.142.136 | 77.70.142.139 | NG
77.70.128.0 | 77.70.143.255 | LU | 77.70.142.140 | 77.70.142.143 | NO
77.70.128.0 | 77.70.143.255 | LU | 77.70.142.144 | 77.70.142.183 | CD
77.70.128.0 | 77.70.143.255 | LU | 77.70.142.184 | 77.70.142.191 | CM
77.70.128.0 | 77.70.143.255 | LU | 77.70.142.192 | 77.70.142.199 | IT
77.70.128.0 | 77.70.143.255 | LU | 77.70.142.200 | 77.70.142.215 | BF
77.70.128.0 | 77.70.143.255 | LU | 77.70.142.216 | 77.70.142.223 | ML
77.70.128.0 | 77.70.143.255 | LU | 77.70.142.224 | 77.70.142.239 | NO
77.70.128.0 | 77.70.143.255 | LU | 77.70.142.240 | 77.70.143.7 | UA
77.70.128.0 | 77.70.143.255 | LU | 77.70.143.8 | 77.70.143.11 | NO
77.70.128.0 | 77.70.143.255 | LU | 77.70.143.12 | 77.70.143.15 | LB
77.70.128.0 | 77.70.143.255 | LU | 77.70.143.16 | 77.70.143.95 | FR
77.70.128.0 | 77.70.143.255 | LU | 77.70.143.96 | 77.70.143.103 | CF
77.70.128.0 | 77.70.143.255 | LU | 77.70.143.104 | 77.70.143.111 | GQ
77.70.128.0 | 77.70.143.255 | LU | 77.70.143.112 | 77.70.143.127 | NE
77.70.128.0 | 77.70.143.255 | LU | 77.70.143.128 | 77.70.143.255 | US
77.70.144.0 | 77.70.155.255 | NO | 77.70.152.8 | 77.70.152.11 | SS
77.70.144.0 | 77.70.155.255 | NO | 77.70.152.12 | 77.70.156.127 | NO
193.109.186.0 | 193.109.186.255 | ES | 193.109.186.30 | 193.109.186.30 | PT
193.109.186.0 | 193.109.186.255 | ES | 193.109.186.31 | 193.109.191.255 | US

**Comment by sapics** [comment]
Thank you very much for noticing! I check merge program.

**Comment by sapics** [comment]
I have fixed program. `geo-whois-asn-country` and `geo-asn-country` would be fixed next 20 hours later run.

**Comment by sapics** [comment]
I close this issue as resolved. If you find any overlaps, feel free to reopen this issue or create new issue.
Anyway, thank you for finding overlaps!
