### ISSUE TITLE
How can I deploy this DB manually?

### ISSUE THREAD

**Issue by WindowsRegedit** [sapics/ip-location-db#18]
I think this is a fantastic project.But I want to sync the IP Database locally.Are there any scripts / Github Actions which can sync the database? Thanks!

**Comment by sapics** [comment]
Thanks! You can sync the database in many ways.
For example, you can clone my repository with `git clone https://github.com/sapics/ip-location-db`.
After that, you can sync the database with `git fetch origin` and `git checkout -B main origin/main`.

**Comment by sapics** [comment]
I close this issue, because of no response. For general questions, please ask on stackoverflow or elsewhere.
