### ISSUE TITLE
Incorrect escaping on dbip-city-ipv4.csv

### ISSUE THREAD

**Issue by digipigeon** [sapics/ip-location-db#19]
Hi,

I am not sure if this is something that you can cleanse or not however we are seeing the following error

Line 18183 in dbip-city-ipv4.csv
```
2.90.71.0,2.90.71.255,SA,'Asir Region,,Khamis Mushait,,18.3,42.7333
```

This seems to be the problem with all the `'Asir Region` names, this also seems to affect more than 1 source.
'

**Comment by sapics** [comment]
In general csv formatting, the newline character, double quotation marks, and commas are special characters that should be escaped.
The presence or absence of single quotes does not affect the csv in any way, so if any errors occurred, I guess that a bug exists in the program you have processed.

https://en.wikipedia.org/wiki/Comma-separated_values

**Comment by digipigeon** [comment]
Hi @sapics after looking over this, yes you are correct. This must be a problem with the clickhouse CSV parser.
