### ISSUE TITLE
Longevity 

### ISSUE THREAD

**Issue by quesurifn** [sapics/ip-location-db#2]
Hello again Mate,

It looks like you have a worker to auto-update this database daily. 

CanI count on updated MaxMind data from this repo or do you suggest I spin up my own automated process?

Thanks so much!

**Comment by sapics** [comment]
"I spin up my own automated process" looks better ;)

**Comment by whmountains** [comment]
This seems to be a really high quality library.  I would happily sponsor if such an option were available.

The niche has not yet been filled in the rust community as far as I can tell.  Improve the documentation, maybe polish a few rough edges, and this could really go places.

**Comment by sapics** [comment]
Thank you @whmountains for your suggestion!
I am really honored. I will search the sponsor method in github soon.

Sorry for low quality documentation.
I am not good at English, but I will improve the documentation.
If you have any ideas to improve the documentation, please let me know.
