### ISSUE TITLE
I want to create my own version

### ISSUE THREAD

**Issue by sukeshpabolu** [sapics/ip-location-db#21]
Hi,
You have done fantastic work but I have one question. How can I create my own version of ip location db. Is it possible for you to reveal the script that you are using to generate this csvs. Atleast, asn-country-ipv4 csv?

**Comment by sapics** [comment]
Thanks! I have no plan to publish the script.

**Comment by sukeshpabolu** [comment]
Hi, I don't need the script but we need sources. at least for asn-country-ipv4 ? I really need it for a project I am doing.

**Comment by sapics** [comment]
You can download csv file which created by the script.
https://cdn.jsdelivr.net/npm/@ip-location-db/asn-country/asn-country-ipv4.csv

I guess that you need more data than this csv, but I have created only 3 types csv which are ip-asn, ip-country, ip-city.
So, the other database would be better for you. For example, if you need bulk information on ip-asn+country, https://iptoasn.com/ might help you.
