### ISSUE TITLE
IP6 numbers don't seem correct.

### ISSUE THREAD

**Issue by Floccinaucinihilipilification11** [sapics/ip-location-db#23]
In your readme, you say:
ipv6-num: The csv line 42540528726795050063891204319802818560,42540528806023212578155541913346768895,JP means that ip addresses between 2001:200:: and 2001:200:ffff:ffff:ffff:ffff:ffff:ffff inclusive are JP country_code. (42540528726795050063891204319802818560 is the number format of the IP address 2001:200::)

But in your spreadsheets, the numbers don't seem to correlate to the correct IP addresses. For example, in the asn-country-ip6.csv file, the first entry is:
2001:200::	2001:200:ffff:ffff:ffff:ffff:ffff:ffff	JP

But in the corresponding number spreadsheet, asn.country-ip6-num.csv, the first entry is:
42540528726795000000000000000000000000.00	42540528806023200000000000000000000000.00	JP

which are not the correct 128 bit numbers for the above IP6 addresses.

Thoughts?

**Comment by sapics** [comment]
In my browser, the first entry is
42540528726795050063891204319802818560,42540528806023212578155541913346768895,JP
from
https://raw.githubusercontent.com/sapics/ip-location-db/main/asn-country/asn-country-ipv6-num.csv

I guess that it is come from spreadsheet rounding error. Please try to read in text editor.

**Comment by Floccinaucinihilipilification11** [comment]
You are right, It's rounding in my spreadsheet. I never considered that to be a possibility Sorry to bother you.
