### ISSUE TITLE
invalid digit found in string

### ISSUE THREAD

**Issue by whmountains** [sapics/ip-location-db#3]
Hello there!  Thanks so much for putting this tool together.

I am trying to load the ip2asn ipv4 database but am getting the following error:

`invalid digit found in string`

Any ideas what might be causing this?  Thanks!

**Comment by sapics** [comment]
Hi @whmountains !

These links work well for me.
https://cdn.jsdelivr.net/npm/@ip-location-db/asn-country/asn-country-ipv4.csv
https://cdn.jsdelivr.net/npm/@ip-location-db/asn-country/asn-country-ipv4-num.csv

If you want to use `digit number`, I guess that https://cdn.jsdelivr.net/npm/@ip-location-db/asn-country/asn-country-ipv4-num.csv is the one what you want

**Comment by whmountains** [comment]
Thanks for getting back to me @sapics !  It will be a couple of weeks before I circle back to this again and try your suggestion, most likely.  If you want to close this issue feel free.

**Comment by sapics** [comment]
I have updated the documentation about csv format, I hope that it would help you.
https://github.com/sapics/ip-location-db#csv-format

I do not care if this issue open, I will keep opening this issue for a while.

**Comment by sapics** [comment]
I'll close this issue but feel free to reopen or create new issue.
