### ISSUE TITLE
dbip-country-ipv6: two entries have a start larger than the end

### ISSUE THREAD

**Issue by Banain** [sapics/ip-location-db#31]
Looks like in the current dbip-country-ipv6.csv two entries have an end entry which is before the start entry.

2001:ad0:cfe:0:d42f:c95b::,2001:ad0:cfe:0:217:28:244:179,RU
2a10:6e40:0:3::,2a10:6e40:0:2:ffff:ffff:ffff:ffff,DE

**Comment by sapics** [comment]
Thank you for finding bugs!
It is my mistake in ipv6 converting program.
Now, I fix it!
