### ISSUE TITLE
Could you release the MMDB files in addition to the CSVs?

### ISSUE THREAD

**Issue by paul-norman** [sapics/ip-location-db#34]
Hello!

Thanks for your great work on this project! I was wondering if you have any plans to build and add the MMDB files to the CDNs in addition to the CSVs?

The reason that I ask is that I have just created a project that uses any of your databases to create a [simple API in Go](https://github.com/paul-norman/ip-location-api). This system is capable of dynamically generating the MMDB files itself after download, **BUT** when I tested it on some tiny AWS instances *(that I use often)*, they simply don't have enough memory available to perform this step *(as the whole file seems to need loading into memory before saving)*. After they are built, the MMDB files are memory efficient, but creating them on-the-fly is problematic.

I personally only need the databases in PostgreSQL, but I decided to write a tool that would also support MMDB and MySQL so that others might benefit from it too *(SQLite is proving awkward for IPv6!)*. I'd like to make this a little bit better so that it can run on really cheap hardware.

I could create my own pipeline process for this and add them to a CDN myself, but I feel that it would probably be more useful for the community in general if these files were saved directly alongside yours.

Since all of your files are in a standardised format, I would be happy to write you a little tool that takes any one of your files and creates the associated MMDB file from it, something like:

```
ip-database-convert -i dbip-city-ipv4.csv -o dbip-city-ipv4.mmdb -t city
```

So that you could incorporate it into your offline build process easily.

Let me know if it's something that you might be interested in *(don't worry if not!)*. Thanks for the great work!

------
Aside: I know that there are other projects that provide an API (e.g. [Ip-geo-API](https://github.com/realchandan/Ip-geo-API)), and others that convert your files to MMDB (e.g. [IP-Geolocation-DB](https://github.com/HostByBelle/IP-Geolocation-DB)), but they only support a small subsection of your files. I would like to support **ALL** of them *(including city files)*.

**Comment by sapics** [comment]
Thank you for your feature request!
It looks great to provide MMDB files in this repository.
I will be late because I have been busy for the past few months, but I would like to create it.

**Comment by paul-norman** [comment]
Sorry for my slow reply, it's been a busy week.

Great to hear that you'd be open to adding MMDB files to your build process! The main thing to consider then is what would you like the MMDB file structure for each file to look like? *(there are currently 3 to consider: country, asn and city)*

In my API system, I attempted to replicate the data structure of some existing MMDB files from Maxmind, but I don't think that there's any requirement / benefit in doing this *(since we don't have the data to populate the fields properly anyway)*, and the files will be smaller if the MMDB structure was "flat" instead. Conversely, we may wish to attempt to maintain compatibility with existing APIs written for several popular programming languages to consume MMDB files already, so it might be worth maintaining some kind of standard structure?

For now, I've made a quick tool, [ip-location-to-mmdb](https://github.com/paul-norman/ip-location-to-mmdb), which will create MMDB files from CSV files for each case, but flatten the file structure. For a single record of each type of database, an MMDB result might look like:

COUNTRY:

```json
{
	"country": "GB"
}
```

ASN:

```json
{
	"number":	20712
	"organisation":	"Andrews & Arnold Ltd"
}
```

CITY:

```json
{
	"city":		"London",
	"postcode":	"",
	"timezone":	"",
	"country":	"GB",
	"latitude":	51.5143,
	"longitude":	-0.0912244,
	"state_1":	"England",
	"state_2":	"",
}
```

This can easily be changed in future.

----

**ASIDE:** The Maxmind format for their MMDB files is normally a lot more complex, for example a `country` result looks more like:

```json
{
	"continent": {
		"code": "EU",
		"geoname_id": "6255148",
		"names": {
			"de": "Europa",
			"en": "Europe",
			"es": "Europa",
			"fr": "Europe",
			"ja": "ヨーロッパ",
			"pt-BR": "Europa",
			"ru": "Европа",
			"zh-CN": "欧洲"
		}
	},
	"country": {
		"geoname_id": 2635167,
		"iso_code": "GB",
		"names": {
			"de": "Vereinigtes Königreich",
			"en": "United Kingdom",
			"es": "Reino Unido",
			"fr": "Royaume-Uni",
			"ja": "イギリス",
			"pt-BR": "Reino Unido",
			"ru": "Великобритания",
			"zh-CN": "英国"
		}
	},
	"registered_country": {
		"geoname_id": 6252001,
		"iso_code": "US",
		"names": {
			"de": "USA",
			"en": "United States",
			"es": "Estados Unidos",
			"fr": "États-Unis",
			"ja": "アメリカ合衆国",
			"pt-BR": "Estados Unidos",
			"ru": "США",
			"zh-CN": "美国"
		}
	}
}
```

which I feel is a bit overkill *(especially since we lack almost all of that data)*, but I could certainly implement something more like this instead if preferred.

**Comment by paul-norman** [comment]
> Your repository is really great! It includes PostgreSQL, MySQL and SQLite!

Thanks, I hope that one day someone will find / use it!

I don't work with large numbers *(nor IP addresses normally)*, so I don't know the methods to make IPv6 converted IP addresses work properly with SQLite *(it only supports int64s and nothing larger)*. If you know the correct structure *(columns and query)* to use in that case, I'll update that code to fix it.

**Comment by sapics** [comment]
Thank you for considering about field names and creating the tool!

I have two things I would like to discuss with you.
The first is field names, as you noted.
I would also like to make the database "flat" as you suggested.
This is what I created as test. How about this? https://github.com/sapics/ip-location-db/tree/mmdb-test

The name of "autonomous_system_number" is longer than what I want, but I use this name because GeoLite2-asn-mmdb used this name.

COUNTRY:

```json
{
	"country_code": "GB"
}
```

ASN:

```json
{
	"autonomous_system_number":	20712
	"autonomous_system_organization":	"Andrews & Arnold Ltd"
}
```

CITY:

```json
{
	"city":		"London",
	"postcode":	"",
	"timezone":	"",
	"country_code":	"GB",
	"latitude":	"51.5143",
	"longitude": "-0.0912244",
	"state1":	"England",
	"state2":	"",
}
```


The second is the format of latitude and longitude.
I adopted "string" format for latitude and longitude instead of float format.
There are some rows where the latitude and longitude was empty. (for example: 62.73.8.0)
When using float format, I am not sure whether an empty string would be converted to 0 or null, so I temporarily changed it to string format to be on the safe side.
If it is possible to convert an empty string to null, I would also like to adopt the float format, do you know if this is possible?

**Comment by paul-norman** [comment]
Thanks for integrating this so quickly!

I've made the naming changes that you suggested to all of the items, and have made the lon / lat fields strings because there's [no specific null type](https://github.com/maxmind/mmdbwriter/blob/main/mmdbtype/types.go) _(nor is this possible directly in Go - empty float values just become 0)_. It would be possible to give each record its own structure _(i.e. use a float when data is present and use a string when missing)_, but I think that this might be confusing for users of the MMDB files *(generate parsing errors)* and it would be better to just leave handling of empty values up to the user upon retrieval.

I'm happy to update the format again if that's a route you'd like to take though. It would also be possible to include float and string versions of the lon / lat fields, but the file size would increase.

Let me know when you have something working that you're happy with and I'll update my API to use the MMDB files from your system rather than generating its own.

**Comment by sapics** [comment]
Thanks for quick answer!

I understand there is not "null" type!
I am now creating an automation flow.

By the way, I am not familiar with golang and mmdb, is it possible fix? (https://github.com/sapics/ip-location-to-mmdb/commit/0787843cf766942131ac49069da9f4e143757ecc)
It makes smaller mmdb file size, if it is possible.

**Comment by paul-norman** [comment]
I've made a new version where you can manually set the MMDB record size (24, 28 or 32) using the `-r` flag. If you omit this flag it will choose 24 for country and asn files and 28 for city files. 

When I tested (using the dpip-city file) I don't think that this will work at 24, you'll just get the error:

```
exceeded record capacity by attempting to write (6509723, 16777238) to node with 24 bit record size; try increasing RecordSize or reducing the size of the database
```

I haven't tested it on the others though (you might be able to make some smaller).

**Comment by sapics** [comment]
Thanks to your help, I am able to add mmdb files to the main branch today!
It will update daily, if there are no bugs ;)
When I confirm the daily update, I will add links for mmdb file in README.

I also added the links to your repository in Tools & Applications chapter of the README.
I am not very good at English, so if there are any changes you would like to make in the description or anything else, please feel free to contact me.

**Comment by paul-norman** [comment]
**Great work**, thanks so much for adding that!

I'll update my API tool to make use of it as soon as I get time (hopefully over the weekend).

I can certainly help you improve the English of the main README file. In addition to that README, shall I also look at making the README files in the individual folders specific to their files? It would be far more useful if the content of those READMEs was specific to those files alone... If you're happy for me to do that I can make a fork and take a look over the weekend. I might need some extra information from you about the individual sources to do it properly, but I think that it would be useful.

Do you want to aim for [multilingual README support](https://github.com/jonatasemidio/multilanguage-readme-pattern)? To begin with, you could add a Japanese version in addition to the English, and I might be able to persuade some friends to translate into a few other popular languages once they're done too.

**Comment by sapics** [comment]
Making the individual README looks great!
Currently, the README for each folder is simply a copy of the top README, with the title renamed.
As you say, it is not enough explanation in each folder.
However, if we create everything completely separately, it would be difficult to manage README afterwards.
So I think it would be better to create a DESCRIPTION.md in each folder and copy its contents between the title and listing table in the README.md to show the contents.
I am thinking that which of the three database types (asn, country, city) and license information would be sufficient for DESCRIPTION.md, but is there any other information you think we need?

Creating a multilingual version sounds interesting, but I don't want to do it because it seems too difficult to manage afterwards ;)

**Comment by paul-norman** [comment]
Okay, great I'll have a look at the main `README.md` today. I also completely understand about maintaining multilingual files, we'll avoid that.

> So I think it would be better to create a DESCRIPTION.md in each folder and copy its contents between the title and listing table in the README.md to show the contents

I'm not sure that I follow exactly what you want to do here! Do you want a file named `DESCRIPTION.md` that carries the dynamic information that can be used to build a `README.md` file dynamically in each of those directories? You'd then use this file to create the `README.md` files every night? 

> DESCRIPTION.md, but is there any other information you think we need?

The format that I would probably have personally created for each of the folder-specific `README.md` files would be something like:

```markdown
# File Name

Brief description of the source data (origin / links etc)

## Download

Your table with links to download the relevant files only

## Related Downloads *(if they exist)*

A table with links to other files in the series (e.g. if this were the `dbip-country` folder, include links to the `dbip-asn` and `dbip-city` data files)

## Format Explanation

Explain the fields and usage *(there are 6 options for this, 3 for each of CSV and MMDB - `country`, `asn` and `city`)*

## Licensing Requirements

Brief guide to any license information / restrictions for this file
```

This does create a large number of unique `README.md` files, but they would then be very useful / relevant and wouldn't need updating often *(if ever?)*. Within files like this, the format explanation would be the only bit that is repeated often / generically, so I would have thought that dynamic building would be a little redundant. There are 27 versions to maintain though, so I see your point in wanting to keep it simple, but if you add another, there are then relevant templates to copy-paste from.

If this information was included in the sub-folders, the main `README.md` file could be simplified a little too - it wouldn't need the "CSV format" section nor the "Databases referenced in this project" sections *(just instructions to view these details in each folder)*. For this reason, I'll hold off doing much until you decide exactly how you'd like the `README.md` files to be. I might make one or two as examples when I fork the repo so that you can see what you think first.

*(It's a little difficult for me to guess what might be best, because I don't have the details of your build pipeline.)*

**Comment by sapics** [comment]
> Do you want a file named DESCRIPTION.md that carries the dynamic information that can be used to build a README.md file dynamically in each of those directories? You'd then use this file to create the README.md files every night?

Yes, that's right!

> The format that I would probably have personally created for each of the folder-specific README.md files would be something like:

Thanks! Looks great!
As you noticed, it will be better to create `DESCRIPTION.md` by myself with your opinion, because I need to make a build process.

**Comment by paul-norman** [comment]
I've made a [fork of your repo](https://github.com/paul-norman/ip-location-db/tree/readme-improvement) where I've taken a first pass at updating the main README.md structure.

For now, I've just cleaned up the file a little (bringing in the MMDB files into the downloads table) and created a few separate files with more generic advice *(`IP_FORMAT.md`, `COUNTRY.md`, `ASN.md` and `CITY.md`)* which are just linked to. However, these files could be merged in / replaced later. 

The specific DB information isn't there yet, but the idea would be to put that into the nested directories anyway.

If you let me know roughly how you are planning to merge these files *(e.g. parse files into variables and the replace them into files using variable names, e.g. `${varname}`)* then I will have a think of improved structure for the process. The partial files don't need to be in markdown, they could be in any format you like *(e.g. raw JS files or PHP files depending upon your build system language)*. All of the partial information could really just be stored in a single file with many variables that you parse once and reference as necessary...

**Comment by sapics** [comment]
Thanks a lot!!
It is very impressive, very nicely formatted and easier to read!
I changed my plan when I saw the .md files you created.
I would like to take a time to reconsider what kind of md file would be better.

When you make a PR for markdown files, it would be helpful if you could put all files such as README.md, ASN.md, etc. in a folder such as `doc`.
Because the `Daily Update` will automatically overwrite the README.md file.

**Comment by paul-norman** [comment]
Glad that we're heading in the right direction!

I wasn't planning on those partial files *(`IP_FORMAT.md`, `COUNTRY.md`, `ASN.md` and `CITY.md`)* existing in the long term they're just for show really, I think that they'd be better off generated...

I think that in each of the folders (wherever there should be a `README.md` file) we should instead create a `README.tpl` file *(exact name is unimportant)* and that would use variables *(I'm using a JS-style format for illustration here: `${variable}`)*. Using the main `README.tpl` file as a truncated example, the first few lines might look like:

```Markdown
# ip-location-db

This project provides IP to location databases in CSV and MMDB formats.

## Available database downloads

There are 3 types of IP database in this repository: `country`, `asn` and `city` files. All have their own 
standard format. Please use the provided CDN links rather than directly linking to files in this repository.

### Country

These files map IP ranges to country codes:

${download-table-header}
${asn-country-table-row}
${geo-asn-country-table-row}
${geo-whois-asn-country-table-row}
...
```

And then, in a single file *(name and format of your choosing)*, but something like `README.data` we add all of the data in reusable chunks to be used in **any** of the `.tpl` files:

```
--- ${download-table-header} ---
| Database | Type | Licence | Updated | IPv4 | IPv6 | IPv4-num | IPv6-num |
|---|---|---|---|---|---|---|---|
--- ${asn-country-table-row} ---
| ASN <br>[![npm version](https://img.shields.io/npm/v/@ip-location-db/asn-country?color=success&style=flat-square&label=CSV)](https://www.npmjs.com/package/@ip-location-db/asn-country)<br>[![npm version](https://img.shields.io/npm/v/@ip-location-db/asn-country-mmdb?color=success&style=flat-square&label=MMDB)](https://www.npmjs.com/package/@ip-location-db/asn-country-mmdb) | [Country](COUNTRY.md)| [CC0](https://creativecommons.org/publicdomain/zero/1.0/deed) | Daily | [CSV](https://cdn.jsdelivr.net/npm/@ip-location-db/asn-country/asn-country-ipv4.csv)<br>[MMDB](https://cdn.jsdelivr.net/npm/@ip-location-db/asn-country-mmdb/asn-country-ipv4.mmdb) | [CSV](https://cdn.jsdelivr.net/npm/@ip-location-db/asn-country/asn-country-ipv6.csv)<br>[MMDB](https://cdn.jsdelivr.net/npm/@ip-location-db/asn-country-mmdb/asn-country-ipv6.mmdb) | [CSV](https://cdn.jsdelivr.net/npm/@ip-location-db/asn-country/asn-country-ipv4-num.csv) | [CSV](https://cdn.jsdelivr.net/npm/@ip-location-db/asn-country/asn-country-ipv6-num.csv) |
--- ${geo-asn-country-table-row} ---
| GeoFeed + ASN<br>[![npm version](https://img.shields.io/npm/v/@ip-location-db/geo-asn-country?color=success&style=flat-square&label=CSV)](https://www.npmjs.com/package/@ip-location-db/geo-asn-country)<br>[![npm version](https://img.shields.io/npm/v/@ip-location-db/geo-asn-country-mmdb?color=success&style=flat-square&label=MMDB)](https://www.npmjs.com/package/@ip-location-db/geo-asn-country-mmdb) | [Country](COUNTRY.md)| [CC0](https://creativecommons.org/publicdomain/zero/1.0/deed) | Daily | [CSV](https://cdn.jsdelivr.net/npm/@ip-location-db/geo-asn-country/geo-asn-country-ipv4.csv)<br>[MMDB](https://cdn.jsdelivr.net/npm/@ip-location-db/geo-asn-country-mmdb/geo-asn-country-ipv4.mmdb) | [CSV](https://cdn.jsdelivr.net/npm/@ip-location-db/geo-asn-country/geo-asn-country-ipv6.csv)<br>[MMDB](https://cdn.jsdelivr.net/npm/@ip-location-db/geo-asn-country-mmdb/geo-asn-country-ipv6.mmdb) | [CSV](https://cdn.jsdelivr.net/npm/@ip-location-db/geo-asn-country/geo-asn-country-ipv4-num.csv) | [CSV](https://cdn.jsdelivr.net/npm/@ip-location-db/geo-asn-country/geo-asn-country-ipv6-num.csv) |
--- ${geo-whois-asn-country-table-row} ---
| GeoFeed + Whois + ASN<br>[![npm version](https://img.shields.io/npm/v/@ip-location-db/geo-whois-asn-country?color=success&style=flat-square&label=CSV)](https://www.npmjs.com/package/@ip-location-db/geo-whois-asn-country)<br>[![npm version](https://img.shields.io/npm/v/@ip-location-db/geo-whois-asn-country-mmdb?color=success&style=flat-square&label=MMDB)](https://www.npmjs.com/package/@ip-location-db/geo-whois-asn-country-mmdb) | [Country](COUNTRY.md)| [CC0](https://creativecommons.org/publicdomain/zero/1.0/deed) | Daily | [CSV](https://cdn.jsdelivr.net/npm/@ip-location-db/geo-whois-asn-country/geo-whois-asn-country-ipv4.csv)<br>[MMDB](https://cdn.jsdelivr.net/npm/@ip-location-db/geo-whois-asn-country-mmdb/geo-whois-asn-country-ipv4.mmdb) | [CSV](https://cdn.jsdelivr.net/npm/@ip-location-db/geo-whois-asn-country/geo-whois-asn-country-ipv6.csv)<br>[MMDB](https://cdn.jsdelivr.net/npm/@ip-location-db/geo-whois-asn-country-mmdb/geo-whois-asn-country-ipv6.mmdb) | [CSV](https://cdn.jsdelivr.net/npm/@ip-location-db/geo-whois-asn-country/geo-whois-asn-country-ipv4-num.csv) | [CSV](https://cdn.jsdelivr.net/npm/@ip-location-db/geo-whois-asn-country/geo-whois-asn-country-ipv6-num.csv) |
```

Of course the real files will be much longer. These variables can then be used in any `.tpl` file and dynamically create the `README.md` files from the reusable chunks.

I guess the process would have to be: parse `README.data` into a map of variable names, scan the project for the `<NAME>.tpl` files, find and replace all variables into them, and then save that data as the final `<NAME>.md` files. This would leave you with quite a lot of parsing and building, but the end result should be quite "neat" with relatively little de-duplication.

Let me know what you think, and if you like it, I'll organise my branch into something that can be used in that way.

**Comment by sapics** [comment]
Thanks!!
It is far better than anything I could have imagined!
I completely agree with your thoughts!

**Comment by sapics** [comment]
By the way, since the mmdb files were smaller than the csv files, I thought the asn-country-mmdb and asn-mmdb (and so on) directories were unnecessary except for city data, so I would like to merge them into the respective asn-country and asn directories.

**Comment by paul-norman** [comment]
Sorry, only got around to this tonight. I've created the template files (`README.tpl`), the main data source (`README.data`), a tool to compile them (`tools/create-readme.js`) and raised a pull request.

Let me know if there are any issues.

**Comment by sapics** [comment]
Thank you for great works! I will create the automation process from your works!

**Comment by sapics** [comment]
I update all README files now! Thanks a lot for helping!

**Comment by paul-norman** [comment]
Thanks for adding the MMDB files to your project, when I get the time I'll update my API tool to make use of them!
