### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by tbussmann** [sapics/ip-location-db#37]
Is there a changelog for the generation scripts and collection of sources available anywhere? As the Github repo is regularly rebased, not even the changes in the readme files can be tracked over time.

For example:
`geo-whois-asn-country` grew by an unusual 1.26MB between 2.3.2024090718 and 2.3.2024091008, and there were no updates in between, so I was curious what changes might have happened here. Digging further, I find a possible cause in the README.md of 2.3.2024091218, which may have been documented a bit after the change:

```diff
- Created by merging GeoFeed database from [OpenGeoFeed](https://opengeofeed.org/).
+ Created by merging GeoFeed database from [OpenGeoFeed](https://opengeofeed.org/) and [Collections of provider geofeed](https://github.com/HostByBelle/ip-db-test-data) and so on.
```

and issue #36 which gives some details to this as well.

I would very much like to see a changelog (as a separate file or in the existing readme files) containing something like the following (e.g. reconstructed entries - may not be correct)

2024-09-13: fixed errors in country codes ZN, UK, XK, FL #36
2024-09-10: added new GeoFeed providers OpenGeoFeed, That-Guy-Jack/geofeed
2024-08-20: added links to mmdb files to main readme #34
2024-08-14: added generation of mmdb files #34
2023-05-17: fixed overlapping ip ranges #17

Thank you for considering this.

**Comment by sapics** [comment]
Indeed! It is the good idea!
We cannot keep git histories because of the size limitation as #4.
The CHANGELOG is more necessary than the other repositories because we lost git histories. I will create in hours.

**Comment by sapics** [comment]
Now, I have added the CHANGELOG!

**Comment by sapics** [comment]
I have closed this issue as closed. Feel free to reopen this or create new issue, if there are any issues.
