### ISSUE TITLE
Really useful, but will probably get shut down at some point.

### ISSUE THREAD

**Issue by patleb** [sapics/ip-location-db#4]
I took a look at the repo history and I saw that you don't rewrite the history when updating the databases... meaning that this repo will eventually reach a size that github won't allow to continue hosting for free. Also, at this rate of updates, I think that it'll happen sometime this year: the repo was around 3.7GB 3 months ago and the maximum is around 5GB per repository.

**Comment by sapics** [comment]
Thanks @patleb for noticing!

I have no time to fix now, thus, I delete all history with
https://gist.github.com/heiswayi/350e2afda8cece810c0f6116dadbe651
as temporary solution.

After some days later, I will fix with github actions as permanent solution.

**Comment by sapics** [comment]
Today, I create github actions, it looks work well. Thanks again!

**Comment by patleb** [comment]
No problem and thanks to you as well for making these databases easily available!
