### ISSUE TITLE
Webnet77 is dead

### ISSUE THREAD

**Issue by tdulcet** [sapics/ip-location-db#6]
Webnet77 seems to be dead. The database has not updated since April 16 and the website no longer exists. Also see [here](https://about.ip2c.org/#news). You could consider using [IP2Location](https://lite.ip2location.com/ip2location-lite) as a replacement.

**Comment by sapics** [comment]
Thanks for noticing about webnet77!
I would like to remove it from repository.
And IP2Location looks great!

**Comment by sapics** [comment]
I have deleted the webnet77.

**Comment by sapics** [comment]
Redistributing the database `Ip2Location Lite` in this repository seems to be difficult based on the following FAQ.

https://lite.ip2location.com/faq

Q: Can I redistribute the database in my client application?
A: You can redistribute one copy of the LITE database with your application with attribution. However, you need to inform all users to register for an individual license in https://lite.ip2location.com/ to download monthly updates. Third party database repository is not allowed.
