### ISSUE TITLE
Consider open sourcing the scripts used to update these databases

### ISSUE THREAD

**Issue by tdulcet** [sapics/ip-location-db#7]
Please consider open sourcing the scripts used to automatically generate/update these databases. I would like to create my own repository with all the databases uncompressed and in a slightly different format for a project I am working on. I would also like to provide the localized versions of the MaxMind GeoLite2 database. You have already done all the work to automate this, so it would be very helpful to not have to reinvent the wheel.

Thanks for creating this and for your consideration!

**Comment by sapics** [comment]
I am not good at English. Thus, I used google translate. I'm sorry if you are rude.
----

Thank you for your interest.
There are no plans to publish an update script at this time.

Reason
(1): Since the amount of data required for updating is very large, I would like to avoid a large amount of traffic from the forked repository by publishing the script.
(2): I didn't plan to publish it for the reason of (1), so I wrote the script comment and git log in Japanese, so I need to rewrite it for publication in English. I don't want to do it because it's hard to rewrite.

**Comment by extrawurst** [comment]
my 2cents:

(1) a script itself should not create traffic
(2) I guess as long as your script code runs comments (heck even variable names) in another language should not be a problem

**Comment by tdulcet** [comment]
> Thank you for your interest.
> There are no plans to publish an update script at this time.

Thanks for at least considering it. 

> (1): Since the amount of data required for updating is very large, I would like to avoid a large amount of traffic from the forked repository by publishing the script.

I have no plans to publish the databases to NPM or anywhere similar. The fork would only be for my personal use, for a browser WebExtension/add-on I am developing to download. Just forking the repository alone would not create any traffic, as the user would still need to setup/enable a CI service, enter the API keys for the services, etc.

My preferred choice would be to download the databases directly from the respective sources, but they all seem to use gzip/zip compression and many have download limits, both of which are unfortunately prohibitive for my use case. This repository of course solves the latter problem and my fork would fully solve the former.

> (2): I didn't plan to publish it for the reason of (1), so I wrote the script comment and git log in Japanese, so I need to rewrite it for publication in English. I don't want to do it because it's hard to rewrite.

There would be no need to rewrite anything, as I only care about the code. I could always use Google Translate if needed. 😉 Please feel free to publish the script as is.

For reference, the extension I am developing shows the location of all the connections/requests on the current page, among other info. I am currently only able to show the country/flag, as those are the only databases that are available uncompressed, although I would like to be able to show the full localized location. Here is an example of what it looks like for this GitHub page:
![image](https://user-images.githubusercontent.com/15305150/123542996-6c7cf600-d701-11eb-96c1-97db0c25f8cc.png)

**Comment by sapics** [comment]
Thanks for very quick response @extrawurst and @tdulcet!


@extrawurst
I agree with you, script itself has no traffic problem;) But I am still afraid free server's cost.
For updating the ip-location database, it needs to download texts data which are over Giga-Bytes which are provided by many free servers. It is easy to work every day by forking.


@tdulcet
Is it means that you want to download without zip?
I guess that you can download country database directly from
https://cdn.jsdelivr.net/npm/@ip-location-db/geo-whois-asn-country/geo-whois-asn-country-ipv4.csv
or
https://raw.githubusercontent.com/sapics/ip-location-db/master/geo-whois-asn-country/geo-whois-asn-country-ipv4.csv.
Am I misunderstanding something?

**Comment by tdulcet** [comment]
> @tdulcet
> Is it means that you want to download without zip?

Yes, among other things...

> I guess that you can download country database directly from
> https://cdn.jsdelivr.net/npm/@ip-location-db/geo-whois-asn-country/geo-whois-asn-country-ipv4.csv
> or
> https://raw.githubusercontent.com/sapics/ip-location-db/master/geo-whois-asn-country/geo-whois-asn-country-ipv4.csv.

Yes, that is what I did for the above prototype. However, the two databases that include the full location (with the city and state/province) are only provided in gzip (`.gz`) compressed format by this repository.

> Am I misunderstanding something?

The compression is only one of several changes I would like to make (see original issue above). Most of them I believe would only be practical to make in a fork/separate repository, so as not to interfere with any existing users of this repository.

In addition, similar to #2, if I am going to use this in a production program, I need to be able to guarantee reliability for users, which I can of course only do with my own repository.

This is a great repository, which you obviously went to a lot of work to create and automate everything. I just would like to build on your work and tailor the databases for use by my extension, without having to reimplement your scripts from scratch. It would be very helpful for me and likely other developers.

**Comment by sapics** [comment]
@tdulcet

I understand what you want, now ;)

This repository provide city data by compressed format (.gz), because of the GitHub restrictions.
GitHub want to a file smaller than 50MB and block a file larger than 100MB (https://docs.github.com/en/github/managing-large-files/working-with-large-files/conditions-for-large-files).

It would be possible to make a file larger than 100MB by Git-LFS.
I did not use Git-LFS because I was afraid that using Git-LFS in automation system would cause an error.

And, npm file size limit might be an issue, also. (Sorry, I don't remember well)

**Comment by tdulcet** [comment]
@sapics - Interesting, thanks for the info. Git LFS would likely not work either, as users are limited to just [1 GB of bandwidth](https://docs.github.com/en/billing/managing-billing-for-git-large-file-storage/viewing-your-git-large-file-storage-usage) a month. It seems to be more designed for large files that are rarely modified and infrequently downloaded. ([This](https://stackoverflow.com/a/34780618) might be an alternative solution for you, so that the databases would at least automatically be decompressed when people clone the repository, although it would not help with my use case.)

If you do open source your scripts, I will probably host my repository/databases on GitLab or Bitbucket. GitLab has no maximum file size, just a [10 GB repository size limit](https://docs.gitlab.com/ee/user/gitlab_com/index.html#account-and-limit-settings). Bitbucket has [1 GB file size](https://support.atlassian.com/bitbucket-cloud/docs/what-kind-of-limits-do-you-have-on-repositoryfile-size/) and 2 GB repository size limits.

**Comment by extrawurst** [comment]
I really do not understand why we need to discuss how people *would* handle the big file sizes - open sourcing the scripts has nothing to do with this IMO

**Comment by tdulcet** [comment]
@sapics - By closing this issue, does that mean you are not going to open source/publish the scripts? If so, is there anything we could do to change your mind? @extrawurst made some really good points above.

**Comment by extrawurst** [comment]
@tdulcet that is really awesome! Thanks for doing that. I will switch my https://github.com/extrawurst/ip2country over to your repo
