### ISSUE TITLE
Use 7z

### ISSUE THREAD

**Issue by realchandan** [sapics/ip-location-db#9]
Hi there,

I have downloaded a database file from here. and I have noticed you are using `.gz` archive.
I have unarchived _geolite2-city-ipv4-num.csv.gz_ which was 43.6 MB, and got _geolite2-city-ipv4-num.csv_ of size 229.1 MB, then archived _geolite2-city-ipv4-num.csv_ using 7z and got a new archive with size 22.8 MB.

I think 7z is a better compression method/format to use instead of .gz .

here, 1 MB = 1,000,000 bytes not 1,048,576 bytes

Thanks,
Chandan

**Comment by sapics** [comment]
Thanks @realchandan, looks good!
I will add `.7z` compression type in some days. (For existing users, we need to keep `.gz` file for consistency.)

**Comment by sapics** [comment]
Now, I have added '.7z' compression type!
